# Generated by Django 6.0.6 on 2026-06-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='姓名', max_length=50, verbose_name='姓名')),
                ('phone', models.CharField(db_column='手机号', max_length=20, verbose_name='手机号')),
                ('relationship', models.CharField(db_column='身份关系', max_length=50, verbose_name='身份关系')),
                ('building', models.CharField(db_column='楼栋', max_length=50, verbose_name='楼栋')),
                ('unit', models.CharField(db_column='单元', max_length=50, verbose_name='单元')),
                ('room', models.CharField(db_column='房号', max_length=50, verbose_name='房号')),
                ('property_type', models.CharField(db_column='房屋属性', max_length=20, verbose_name='房屋属性')),
            ],
            options={
                'verbose_name': '业主/租户信息',
                'verbose_name_plural': '业主/租户信息',
                'db_table': 'PI',
            },
        ),
    ]
