# Generated by Django 6.0.6 on 2026-06-17 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pi',
            options={'verbose_name': '信息统计', 'verbose_name_plural': '信息统计'},
        ),
    ]
